# Data Preprocessing

**Import Modules**

In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

**Import Dataset**

In [2]:
data_url = "https://raw.githubusercontent.com/prasertcbs/basic-dataset/master/Loan-Approval-Prediction.csv"

In [3]:
df = pd.read_csv(data_url)
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

Keep clean data in a separate copy to preserve original data

In [4]:
df_clean = df.copy()
df_clean

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

**.drop_duplicates** removes duplicate values and inplace=True makes it permanent

In [5]:
df_clean.drop_duplicates(inplace = True)
df_clean.shape

(614, 13)

**For Gender column:**

1. Fill null values with mode
2. convert Male/Female = 0/1
3. Change column name to Female

In [6]:
df_clean['Gender'] = df_clean['Gender'].fillna(df_clean['Gender'].mode()[0])
df_clean ['Gender'] = df_clean['Gender'].map({"Male" : 0,"Female" : 1})
df_clean.rename (columns={'Gender' : 'Female'}, inplace = True)
df_clean

,Loan_ID,Female,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,0,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,0,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,0,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,0,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,0,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,1,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,0,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,0,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,0,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,1,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

**For Married column:**

1. Fill null values with mode
2. convert No/Yes = 0/1

In [7]:
df_clean['Married'] = df_clean['Married'].fillna(df_clean['Married'].mode()[0])
df_clean ['Married'] = df_clean['Married'].map({"No" : 0,"Yes" : 1})
df_clean

,Loan_ID,Female,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,0,0,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,0,1,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,0,1,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,0,1,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,0,0,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,1,0,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,0,1,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,0,1,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,0,1,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,1,0,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

**For Education column:**

1. convert Not Graduate/Graduate = 0/1
2. Change column name to Education

In [8]:
df_clean ['Education'] = df_clean['Education'].map({"Not Graduate" : 0,"Graduate" : 1})
df_clean.rename (columns={'Education' : 'Graduate'}, inplace = True)
df_clean

,Loan_ID,Female,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,0,0,0,1,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,0,1,1,1,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,0,1,0,1,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,0,1,0,0,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,0,0,0,1,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,1,0,0,1,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,0,1,3+,1,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,0,1,1,1,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,0,1,2,1,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,1,0,0,1,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

**For Self_Employed column:**

1. Fill null values with mode
2. convert No/Yes = 0/1

In [9]:
df_clean['Self_Employed'] = df_clean['Self_Employed'].fillna(df_clean['Self_Employed'].mode()[0])
df_clean['Self_Employed'] = df_clean['Self_Employed'].map({"No" : 0,"Yes" : 1})
df_clean

,Loan_ID,Female,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,0,0,0,1,0,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,0,1,1,1,0,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,0,1,0,1,1,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,0,1,0,0,0,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,0,0,0,1,0,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,1,0,0,1,0,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,0,1,3+,1,0,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,0,1,1,1,0,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,0,1,2,1,0,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,1,0,0,1,1,4583,0.0,133.0,360.0,0.0,Semiurban,N

**For Loan_Status column:**

1. convert N/Y = 0/1
2. Change column name to Approved

In [10]:
df_clean['Loan_Status'] = df_clean['Loan_Status'].map({"N" : 0,"Y" : 1})
df_clean.rename (columns={'Loan_Status' : 'Approved'}, inplace = True)
df_clean

,Loan_ID,Female,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Approved
0,LP001002,0,0,0,1,0,5849,0.0,NaN,360.0,1.0,Urban,1
1,LP001003,0,1,1,1,0,4583,1508.0,128.0,360.0,1.0,Rural,0
2,LP001005,0,1,0,1,1,3000,0.0,66.0,360.0,1.0,Urban,1
3,LP001006,0,1,0,0,0,2583,2358.0,120.0,360.0,1.0,Urban,1
4,LP001008,0,0,0,1,0,6000,0.0,141.0,360.0,1.0,Urban,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,1,0,0,1,0,2900,0.0,71.0,360.0,1.0,Rural,1
610,LP002979,0,1,3+,1,0,4106,0.0,40.0,180.0,1.0,Rural,1
611,LP002983,0,1,1,1,0,8072,240.0,253.0,360.0,1.0,Urban,1
612,LP002984,0,1,2,1,0,7583,0.0,187.0,360.0,1.0,Urban,1
613,LP002990,1,0,0,1,1,4583,0.0,133.0,360.0,0.0,Semiurban,0

**For Property_Area column:**

Convert it into different columns

In [11]:
df_clean = pd.get_dummies(df_clean, columns = ['Property_Area'],drop_first=False)
df_clean.head()

,Loan_ID,Female,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Approved,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,0,0,0,1,0,5849,0.0,NaN,360.0,1.0,1,False,False,True
1,LP001003,0,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,True,False,False
2,LP001005,0,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,False,False,True
3,LP001006,0,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,False,False,True
4,LP001008,0,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,False,False,True

For each new column map True/False = 1/0

In [12]:
colem = ['Property_Area_Rural', 'Property_Area_Semiurban', 'Property_Area_Urban']

for c in colem:
    df_clean[c] = df_clean[c].astype(int)

df_clean.head()

,Loan_ID,Female,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Approved,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,0,0,0,1,0,5849,0.0,NaN,360.0,1.0,1,0,0,1
1,LP001003,0,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,1,0,0
2,LP001005,0,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,0,0,1
3,LP001006,0,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,0,0,1
4,LP001008,0,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,0,0,1

In [13]:
for j in colem:
    df_clean.rename (columns={j : j[14:]}, inplace = True)

df_clean.head()

,Loan_ID,Female,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Approved,Rural,Semiurban,Urban
0,LP001002,0,0,0,1,0,5849,0.0,NaN,360.0,1.0,1,0,0,1
1,LP001003,0,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,1,0,0
2,LP001005,0,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,0,0,1
3,LP001006,0,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,0,0,1
4,LP001008,0,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,0,0,1

Drop **Loan_ID** column as it has no contribution to approval/rejection

In [14]:
df_clean.drop(columns=['Loan_ID'], inplace=True)
df_clean.head(0)

Empty DataFrame
Columns: [Female, Married, Dependents, Graduate, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Approved, Rural, Semiurban, Urban]
Index: []

In [15]:
df_clean.isnull().sum()

Female                0
Married               0
Dependents           15
Graduate              0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Approved              0
Rural                 0
Semiurban             0
Urban                 0
dtype: int64

**For Dependents column:**

1. Fill null values with mode
2. convert string values ti integer

In [16]:
df_clean['Dependents'] = df_clean['Dependents'].fillna(df_clean['Dependents'].mode()[0])
df_clean['Dependents'] = df_clean['Dependents'].map({"1" : 1,"2" : 2, "3+": 3, "0": 0})
df_clean.head()

,Female,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Approved,Rural,Semiurban,Urban
0,0,0,0,1,0,5849,0.0,NaN,360.0,1.0,1,0,0,1
1,0,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,1,0,0
2,0,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,0,0,1
3,0,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,0,0,1
4,0,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,0,0,1

**For Loan_Amount_Term column:**

1. Fill null values with mode
2. Change column name to Term

In [17]:
df_clean['Loan_Amount_Term'] = df_clean['Loan_Amount_Term'].fillna(df_clean['Loan_Amount_Term'].mode()[0]).astype(int)
df_clean.rename (columns={'Loan_Amount_Term' : 'Term'}, inplace = True)
df_clean.head()

,Female,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Term,Credit_History,Approved,Rural,Semiurban,Urban
0,0,0,0,1,0,5849,0.0,NaN,360,1.0,1,0,0,1
1,0,1,1,1,0,4583,1508.0,128.0,360,1.0,0,1,0,0
2,0,1,0,1,1,3000,0.0,66.0,360,1.0,1,0,0,1
3,0,1,0,0,0,2583,2358.0,120.0,360,1.0,1,0,0,1
4,0,0,0,1,0,6000,0.0,141.0,360,1.0,1,0,0,1

**For LoanAmount column:**

1. Fill null values with median

In [18]:
df_clean['LoanAmount'] = df_clean['LoanAmount'].fillna(df_clean['LoanAmount'].median())
df_clean.head()

,Female,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Term,Credit_History,Approved,Rural,Semiurban,Urban
0,0,0,0,1,0,5849,0.0,128.0,360,1.0,1,0,0,1
1,0,1,1,1,0,4583,1508.0,128.0,360,1.0,0,1,0,0
2,0,1,0,1,1,3000,0.0,66.0,360,1.0,1,0,0,1
3,0,1,0,0,0,2583,2358.0,120.0,360,1.0,1,0,0,1
4,0,0,0,1,0,6000,0.0,141.0,360,1.0,1,0,0,1

**For Credit_History column:**

1. Fill null values with mode
2. Change column name to Credit

In [19]:
df_clean['Credit_History'] = df_clean['Credit_History'].fillna(df_clean['Credit_History'].mode()[0]).astype(int)
df_clean.rename (columns={'Credit_History' : 'Credit'}, inplace = True)
df_clean.head()

,Female,Married,Dependents,Graduate,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Term,Credit,Approved,Rural,Semiurban,Urban
0,0,0,0,1,0,5849,0.0,128.0,360,1,1,0,0,1
1,0,1,1,1,0,4583,1508.0,128.0,360,1,0,1,0,0
2,0,1,0,1,1,3000,0.0,66.0,360,1,1,0,0,1
3,0,1,0,0,0,2583,2358.0,120.0,360,1,1,0,0,1
4,0,0,0,1,0,6000,0.0,141.0,360,1,1,0,0,1

In [21]:
from scipy.stats import chi2_contingency

categorical_features = [
    'Female',
    'Married',
    'Dependents',
    'Graduate',
    'Self_Employed',
    'Credit',
    'Rural',
    'Semiurban',
    'Urban'
]

results = []

for col in categorical_features:

    # Create a contingency table
    table = pd.crosstab(df_clean[col], df_clean['Approved'])

    # Perform chi-square test of independence
    chi2, p_value, dof, expected = chi2_contingency(table)

    results.append({
        'Feature': col,
        'Chi2_Statistic': chi2,
        'P_Value': p_value,
        'Degrees_of_Freedom': dof,
        'Min_Expected_Frequency': expected.min()
    })

chi2_df = pd.DataFrame(results)

chi2_df = chi2_df.sort_values(
    by='P_Value'
).reset_index(drop=True)

chi2_df

,Feature,Chi2_Statistic,P_Value,Degrees_of_Freedom,Min_Expected_Frequency
0,Credit,176.114575,3.418350e-40,1,27.830619
1,Semiurban,10.848078,9.889834e-04,1,72.859935
2,Rural,5.756759,1.642535e-02,1,55.973941
3,Married,4.731876,2.960858e-02,1,66.605863
4,Graduate,4.091490,4.309962e-02,1,41.902280
5,Urban,0.976627,3.230330e-01,1,63.166124
6,Dependents,3.151399,3.688663e-01,3,15.947883
7,Female,0.110879,7.391461e-01,1,35.022801
8,Self_Employed,0.000000,1.000000e+00,1,25.641694

In [22]:
from scipy.stats import chi2_contingency

alpha = 0.05

categorical_features = [
    'Female', 'Married', 'Dependents', 'Graduate',
    'Self_Employed', 'Credit', 'Rural', 'Semiurban', 'Urban'
]

results = []

for col in categorical_features:
    table = pd.crosstab(df_clean[col], df_clean['Approved'])

    chi2, p_value, dof, expected = chi2_contingency(table)

    decision = (
        'Reject H0' if p_value < alpha
        else 'Fail to reject H0'
    )

    results.append({
        'Feature': col,
        'Chi2_Statistic': chi2,
        'P_Value': p_value,
        'Degrees_of_Freedom': dof,
        'Alpha': alpha,
        'Decision': decision
    })

chi2_df = pd.DataFrame(results).sort_values(
    'P_Value'
).reset_index(drop=True)

chi2_df

,Feature,Chi2_Statistic,P_Value,Degrees_of_Freedom,Alpha,Decision
0,Credit,176.114575,3.418350e-40,1,0.05,Reject H0
1,Semiurban,10.848078,9.889834e-04,1,0.05,Reject H0
2,Rural,5.756759,1.642535e-02,1,0.05,Reject H0
3,Married,4.731876,2.960858e-02,1,0.05,Reject H0
4,Graduate,4.091490,4.309962e-02,1,0.05,Reject H0
5,Urban,0.976627,3.230330e-01,1,0.05,Fail to reject H0
6,Dependents,3.151399,3.688663e-01,3,0.05,Fail to reject H0
7,Female,0.110879,7.391461e-01,1,0.05,Fail to reject H0
8,Self_Employed,0.000000,1.000000e+00,1,0.05,Fail to reject H0

In [25]:
from pathlib import Path

# Get the current working directory
BASE_DIR = Path.cwd().resolve()

# Verify that we are inside the data preparation folder
if BASE_DIR.name != "KG_Loan_Data_Preperation":
    raise RuntimeError(
        f"Run this notebook from KG_Loan_Data_Preperation. "
        f"Current directory: {BASE_DIR}"
    )

# Locate the sibling artifacts folder
ARTIFACTS_DIR = BASE_DIR.parent / "KG_Loan_Artifacts"

# Create it if it doesn't exist
ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)

# Save the DataFrame
output_path = ARTIFACTS_DIR / "KG_Loan_Dataset.csv"
df_clean.to_csv(output_path, index=False)